# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-TIFF
version:      0.10
version_from: TIFF.pm
installdirs:  site
requires:
    Tk:                            800.014

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
