/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of TIFF.xs. Do not edit this file, edit TIFF.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "TIFF.xs"
/*
  Copyright (c) 1998 Slaven Rezic. All rights reserved.
  This program is free software; you can redistribute it and/or
  modify it under the same terms as Perl itself.
*/

#include <EXTERN.h>
#include <perl.h>
#include <XSUB.h>

#include <tkGlue.def>

#include "pTk/tkPort.h"
#include "pTk/tkInt.h"
#include "pTk/tkImgPhoto.h"
#include "pTk/imgInt.h"
#include "pTk/tkVMacro.h"
#include "tkGlue.h"
#include "tkGlue.m"

extern int hist_equal;

extern Tk_PhotoImageFormat      imgFmtTIFF;
TkimgphotoVtab *TkimgphotoVptr;
ImgintVtab *ImgintVptr;

DECLARE_VTABLES;

#line 39 "TIFF.c"
XS(XS_Tk__TIFF_getHistEqual); /* prototype to pass -Wmissing-prototypes */
XS(XS_Tk__TIFF_getHistEqual)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Tk::TIFF::getHistEqual()");
    {
	int	RETVAL;
	dXSTARG;
#line 34 "TIFF.xs"
      RETVAL = hist_equal;
#line 51 "TIFF.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Tk__TIFF_setHistEqual); /* prototype to pass -Wmissing-prototypes */
XS(XS_Tk__TIFF_setHistEqual)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Tk::TIFF::setHistEqual(x)");
    {
	int	x = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 42 "TIFF.xs"
      RETVAL = (hist_equal = x);
#line 69 "TIFF.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Tk__TIFF); /* prototype to pass -Wmissing-prototypes */
XS(boot_Tk__TIFF)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Tk::TIFF::getHistEqual", XS_Tk__TIFF_getHistEqual, file);
        newXS("Tk::TIFF::setHistEqual", XS_Tk__TIFF_setHistEqual, file);

    /* Initialisation Section */

#line 49 "TIFF.xs"
 {
  IMPORT_VTABLES;
  TkimgphotoVptr = (TkimgphotoVtab *) SvIV(FindTkVarName("TkimgphotoVtab",5));
  ImgintVptr     = (ImgintVtab *) SvIV(FindTkVarName("ImgintVtab",5));
  Tk_CreatePhotoImageFormat(&imgFmtTIFF);
 }

#line 99 "TIFF.c"

    /* End of Initialisation Section */

    XSRETURN_YES;
}

